export const environment = {
    DEV: false,

    ADULTCOLO_STORAGE_KEY_PREFIX: 'adultcolo-',
    PLAYER_STORAGE_KEY_PREFIX: 'adultcolo-player',

    MIN_PLAYERS_ON_DISPLAY: 3,
    PLAYERS_MIN_NUMBER: 2,
    PLAYERS_MAX_NUMBER: 50,

    TURN_NUMBER_TOTAL: 40,
    ADS_BY_PLAY: [0, 1],
    CARTOONS_BY_PLAY: [0, 1],
    FOR_OR_AGAINSTS_BY_PLAY: [1, 3],
    GAMES_BY_PLAY: [5, 7],
    GENERALS_BY_PLAY: [2, 4],
    INSTEADS_BY_PLAY: [1, 3],
    LISTS_BY_PLAY: [1, 3],
    LONG_WINDEDS_BY_PLAY: [2, 4],
    MOVIES_BY_PLAY: [1, 2],
    SONGS_BY_PLAY: [2, 3],
    MIN_TURNS_AFTER_LONG_WINDED_END:  5,
    MAX_PERCENT_TURNS_BEFORE_ANY_LONG_WINDED_TURN:  0.75,

    TIMER_DEFAULT_TIME: 10,
    TIMER_GAME_TIME: 10,
    TIMER_INTERVAL_IN_MILLI_SECONDS: 10,

    PACKAGE_NAME: 'hyebalare.adultcolo',
    ADMOB_INTERSTITIAL_KEY: 'ca-app-pub-7597539153364224/4220385927'
}