export const environment = {
    DEV: false,

    TURN_NUMBER_TOTAL: 40,
    FOR_OR_AGAINSTS_BY_PLAY: [1, 3],
    GAMES_BY_PLAY: [2, 4],
    INSTEADS_BY_PLAY: [1, 3],
    LISTS_BY_PLAY: [1, 3],
    LONG_WINDEDS_BY_PLAY: [2, 4],
    MOVIES_BY_PLAY: [0, 2],
    SONGS_BY_PLAY: [2, 3],
    MIN_TURNS_AFTER_LONG_WINDED_END:  5,
    MAX_PERCENT_TURNS_BEFORE_ANY_LONG_WINDED_TURN:  0.75,

    TIMER_DEFAULT_TIME: 10,
    TIMER_GAME_TIME: 15,
    TIMER_INTERVAL_IN_MILLI_SECONDS: 10,

    ADMOB_INTERSTITIAL_KEY: 'ca-app-pub-7597539153364224/4220385927'
}