export const environment = {
    DEV: true,

    TURN_NUMBER_TOTAL: 10,
    FOR_OR_AGAINSTS_BY_PLAY: [0, 0],
    GAMES_BY_PLAY: [0, 0],
    INSTEADS_BY_PLAY: [0, 0],
    LISTS_BY_PLAY: [0, 0],
    LONG_WINDEDS_BY_PLAY: [10, 10],
    MOVIES_BY_PLAY: [0, 0],
    SONGS_BY_PLAY: [0, 0],
    MIN_TURNS_AFTER_LONG_WINDED_END:  5,
    MAX_PERCENT_TURNS_BEFORE_ANY_LONG_WINDED_TURN:  0.75,

    TIMER_DEFAULT_TIME: 10,
    TIMER_GAME_TIME: 10,
    TIMER_INTERVAL_IN_MILLI_SECONDS: 10,

    ADMOB_INTERSTITIAL_KEY: ''
}